import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsIn, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';
import type { ProcurementStatus } from '../procurement.model';

export const PROCUREMENT_OUTCOME_TARGETS = [
  'SUPPLIER_CONFIRMED',
  'SOURCE_UNAVAILABLE',
  'CANCELLED',
] as const satisfies readonly ProcurementStatus[];

type ProcurementOutcomeTarget = (typeof PROCUREMENT_OUTCOME_TARGETS)[number];

export class TransitionProcurementDto {
  @ApiProperty({ enum: PROCUREMENT_OUTCOME_TARGETS })
  @IsIn([...PROCUREMENT_OUTCOME_TARGETS])
  status!: ProcurementOutcomeTarget;

  @ApiPropertyOptional({
    description: 'Manual supplier confirmation/reference; never generated by automation',
    maxLength: 120,
  })
  @IsOptional()
  @IsString()
  @MinLength(2)
  @MaxLength(120)
  supplierReference?: string;

  @ApiPropertyOptional({ maxLength: 500 })
  @IsOptional()
  @IsString()
  @MinLength(3)
  @MaxLength(500)
  note?: string;
}
